### ISSUE TITLE
Environment build error on windows10

### ISSUE THREAD

**Issue by Tangmc-kawa** [elgw/deconwolf#58] opened 2024-05-31 14:27 UTC
I have installed the dependencies mentioned in INSTALL.md like:
```bash
git clone https://github.com/microsoft/vcpkg
.\vcpkg\bootstrap-vcpkg.bat
.\vcpkg integrate install
.\vcpkg\vcpkg.exe install fftw3
.\vcpkg\vcpkg.exe install tiff
.\vcpkg\vcpkg.exe install gsl
.\vcpkg\vcpkg.exe install opencl
```
and the result here:
```bash
(base) PS E:\TMC\sources> .\vcpkg\vcpkg.exe install fftw3
Computing installation plan...
The following packages are already installed:
    fftw3:x64-windows@3.3.10#8
fftw3:x64-windows is already installed
Total install time: 120 us
fftw3 provides CMake targets:

  # this is heuristically generated, and may not be correct
  find_package(FFTW3 CONFIG REQUIRED)
  target_link_libraries(main PRIVATE FFTW3::fftw3)

  find_package(FFTW3f CONFIG REQUIRED)
  target_link_libraries(main PRIVATE FFTW3::fftw3f)        

  find_package(FFTW3l CONFIG REQUIRED)
  target_link_libraries(main PRIVATE FFTW3::fftw3l)        

fftw3 provides pkg-config modules:

  # fast Fourier transform library
  fftw3

  # fast Fourier transform library
  fftw3f

  # fast Fourier transform library
  fftw3l

(base) PS E:\TMC\sources> .\vcpkg\vcpkg.exe install tiff
Computing installation plan...
The following packages are already installed:     
    tiff[core,zip,lzma,jpeg]:x64-windows@4.6.0#4  
tiff:x64-windows is already installed
Total install time: 102 us
tiff is compatible with built-in CMake targets:   

    find_package(TIFF REQUIRED)
    target_link_libraries(main PRIVATE TIFF::TIFF)

tiff provides pkg-config modules:

    #  Tag Image File Format (TIFF) library.      
    libtiff-4

(base) PS E:\TMC\sources> .\vcpkg\vcpkg.exe install gsl
Computing installation plan...
The following packages are already installed:
    gsl:x64-windows@2.8
gsl:x64-windows is already installed
Total install time: 184 us
The package gsl is compatible with built-in CMake targets:    

    find_package(GSL REQUIRED)
    target_link_libraries(main PRIVATE GSL::gsl GSL::gslcblas)

(base) PS E:\TMC\sources> .\vcpkg\vcpkg.exe install opencl
Computing installation plan...
The following packages are already installed:
    opencl:x64-windows@v2023.02.06#2
opencl:x64-windows is already installed
Total install time: 82.1 us
The package opencl is compatible with built-in CMake targets via CMake v3.6 and prior syntax

    find_package(OpenCL REQUIRED)
    target_link_libraries(main PRIVATE ${OpenCL_LIBRARIES})
    target_include_directories(main PRIVATE ${OpenCL_INCLUDE_DIRS})

and the CMake v3.7 and beyond imported target syntax

    find_package(OpenCL REQUIRED)
    target_link_libraries(main PRIVATE OpenCL::OpenCL)

This package is only an OpenCL SDK. To actually run OpenCL code you also need to install an implementation.

    WINDOWS: implementations typically ship with the drivers of you CPU/GPU vendors.
    LINUX: implementations may be installed from your distro's repo or manually. There are too many to count.       
    APPLE: consult your distribution vendor on the state of OpenCL support: https://support.apple.com/en-us/HT202823
```
but error occurs when i tried to build deconwolf:
```bash
(base) PS E:\TMC\sources\deconwolf\winbuild> cmake .. -G "Visual Studio 17 2022" -T ClangCL -A x64
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- The C compiler identification is Clang 17.0.3 with MSVC-like command-line
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/Microsoft Visual Studio/2022/Community/VC/Tools/Llvm/x64/bin/clang-cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type: Release
-- The CXX compiler identification is Clang 17.0.3 with MSVC-like command-line
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Microsoft Visual Studio/2022/Community/VC/Tools/Llvm/x64/bin/clang-cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Enabling IPO
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
CMake Error at D:/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find FFTW (missing: FFTW_INCLUDE_DIRS FLOAT_LIB FLOAT_OPENMP_LIB)
Call Stack (most recent call first):
  D:/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  util/findFFTW/FindFFTW.cmake:399 (find_package_handle_standard_args)
  CMakeLists.txt:175 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by Tangmc-kawa** [comment] 2024-05-31 15:18
I can solve the PKG_CONFIG error by manually add the path of executive file of it like:
```bash
(base) PS E:\TMC\sources\deconwolf\winbuild> cmake .. -G "Visual Studio 17 2022" -T ClangCL -A x64 -DCMAKE_TOOLCHAIN_FILE="E:/TMC/sources/vcpkg/scripts/buildsystems/vcpkg.cmake" -DPKG_CONFIG_EXECUTABLE="E:/TMC/sources/vcpkg/packages/pkgconf_x64-windows/tools/pkgconf/pkgconf.exe"
-476b-aa73-852cbee152aa-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- Build type: Release
Enabling IPO
CMake Error at D:/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find FFTW (missing: FFTW_INCLUDE_DIRS FLOAT_LIB FLOAT_OPENMP_LIB)
Call Stack (most recent call first):
  D:/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  util/findFFTW/FindFFTW.cmake:399 (find_package_handle_standard_args)
  CMakeLists.txt:175 (find_package)


-- Configuring incomplete, errors occurred!
```
but the FFTW problem persists.

**Comment by elgw** [comment] 2024-06-01 16:27
Hi,

I can confirm that the `CMakeLists.txt` does not work straight out of the box under Windows and that the install instructions are incomplete. 

# Installation hints
At the moment the build process requires some fiddling. These instructions are not complete but I leave them for future reference until this is clean up.
 
The following packages were needed:
```
.\vcpkg\vcpkg.exe install tiff
.\vcpkg\vcpkg.exe install getopt
.\vcpkg\vcpkg.exe install gsl
.\vcpkg\vcpkg.exe install opencl
.\vcpkg\vcpkg.exe install fftw3
.\vcpkg\vcpkg integrate install
```

cmake was called by
```
cmake "-DCMAKE_TOOLCHAIN_FILE=C:/Users/erikw/Desktop/dw-windows/vcpkg/scripts/buildsystems/vcpkg.cmake" -T ClangCL -A x64 ../
```
where the `-DCMAKE_TOOLCHAIN_FILE` path was given by `.\vcpkg\vcpkg integrate install`.

vcpkg had to be enabled manually in Visual Studio.

Under Linker->Input->Additional dependencies, add the following:
```
libomp.lib 
C:\Users\erikw\Desktop\dw-windows\vcpkg\installed\x64-windows\lib\getopt.lib
C:\Users\erikw\Desktop\dw-windows\vcpkg\installed\x64-windows\lib\fftw3.lib
C:\Users\erikw\Desktop\dw-windows\vcpkg\installed\x64-windows\lib\fftw3f.lib
```
Under C/C++ Command line, add:` -fopenmp=libomp /openmp`
Under Linker->Command Line->Additional Options, append `-fopenmp=libomp`

I also had to comment out an `#include <unistd.h>` at one place and remove a `static float max(` function at some point, will fix that in the code base.

I think that a correct `CMakeLists.txt` will resolve all of these things.

## Experimental build
Eventually I got a pair of exe files which I attached.

[dw0.4.0_win11.zip](https://github.com/user-attachments/files/15522337/dw0.4.0_win11.zip)

Using the same benchmark as in the `README.md` I got the following figures

CPU: AMD 5600, GPU: Nvidia GTX 1660 S, 115 iter on the microtubules image:

| Config | time (s) |
| --- | --- |
|`--gpu` |  3.5 |
| `--threads 1` |  81 |
| `--threads 6` |  29 |

It looks like the GPU performance is ok but  the performance did not scale as good on the CPU side. This is probably related to the vcpkg version of fftw3. Ideally dw should use **vcpkg.exe install fftw3[openmp]** but that did not install so the attached build uses  **vcpkg.exe install fftw3**. There is an an [open issue](https://github.com/microsoft/vcpkg/issues/10930) about this, so fingers crossed that it will be resolved.

Please be aware that the windows version is completely untested, and that some of the features are missing (like reporting how much memory was used etc). Also there is no installer for it ...

## Help wanted!
I'd be grateful if someone could give the the `CMakeLists.txt` some love and help out with the windows version of deconwolf.  To create an installer, [NSIS](https://cmake.org/cmake/help/latest/cpack_gen/nsis.html) seems like a good option.

**Comment by elgw** [comment] 2024-06-03 07:24
Here is an installer for windows 11 (probably also windows 10).
[deconwolf_0_4_0_Setup.zip](https://github.com/user-attachments/files/15530176/deconwolf_0_4_0_Setup.zip)

It was produced by NSIS and the following script:
```
Name "deconwolf"

;Icon "todo.ico"

OutFile "deconwolf_0_4_0_Setup.exe"

; The default installation directory
InstallDir $PROGRAMFILES\deconwolf

; Registry key to check for directory (so if you install again, it will 
; overwrite the old one automatically)
InstallDirRegKey HKLM "Software\deconwolf" "Install_Dir"

RequestExecutionLevel admin

!include LogicLib.nsh

;--------------------------------

; Pages

Page components
Page directory
Page instfiles

UninstPage uninstConfirm
UninstPage instfiles

;--------------------------------

; The stuff to install
Section "deconwolf"
 
  SectionIn RO
 
   ; Add the istall dir to the path
  EnVar::SetHKCU
EnVar::Check "Path" "$InstDir"
Pop $0
${If} $0 = 0
  DetailPrint "Already there"
${Else}
  EnVar::AddValue "Path" "$InstDir"
  Pop $0 ; 0 on success
${EndIf}
 
  ; Set output path to the installation directory.
  SetOutPath $INSTDIR
  
  ; Put file there (you can add more File lines too)
  File "dw.exe"
  File "dw_bw.exe"
  File "fftw3f.dll"
  File "getopt.dll"
  File "gsl.dll"
  File "gslcblas.dll"
  File "jpeg62.dll"
  File "liblzma.dll"
  File "libomp.dll"
  File "tiff.dll"
  File "zlib1.dll"

  ; NOTE: Same list for uninstaller
  
  ; Write the installation path into the registry
  WriteRegStr HKLM SOFTWARE\deconwolf "Install_Dir" "$INSTDIR"
  
  ; Write the uninstall keys for Windows
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\deconwolf" "DisplayName" "deconwolf"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\deconwolf" "UninstallString" '"$INSTDIR\uninstall.exe"'
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\deconwolf" "NoModify" 1
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\deconwolf" "NoRepair" 1
  WriteUninstaller "$INSTDIR\uninstall.exe"
  
SectionEnd

; Optional section (can be disabled by the user)
Section "Start Menu Shortcuts (required)"
  SectionIn RO

  CreateDirectory "$SMPROGRAMS\deconwolf"
  CreateShortcut "$SMPROGRAMS\deconwolf\Uninstall.lnk" "$INSTDIR\uninstall.exe" "" "$INSTDIR\uninstall.exe" 0  
  
SectionEnd

;--------------------------------

; Uninstaller

Section "Uninstall"
  
  ; Remove registry keys
  DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\deconwolf"
  DeleteRegKey HKLM SOFTWARE\deconwolf
  
  Delete "$INSTDIR\uninstall.exe"
  Delete "$INSTDIR\dw.exe"
  Delete "$INSTDIR\dw_bw.exe"
  Delete "$INSTDIR\fftw3f.dll"
  Delete "$INSTDIR\getopt.dll"
  Delete "$INSTDIR\gsl.dll"
  Delete "$INSTDIR\gslcblas.dll"
  Delete "$INSTDIR\jpeg62.dll"
  Delete "$INSTDIR\liblzma.dll"
  Delete "$INSTDIR\libomp.dll"
  Delete "$INSTDIR\tiff.dll"
  Delete "$INSTDIR\zlib1.dll"

  RMDir "$INSTDIR"

  ; Remove from path
  EnVar::DeleteValue "Path" "$InstDir"
Pop $0

SectionEnd
```

**Comment by elgw** [comment] 2024-06-03 10:17
I've update the `CMakeLists.txt` file and the `INSTALL.md` now. What is in the repo is the most up-to-date instructions.

**Comment by Tangmc-kawa** [comment] 2024-06-04 02:47
Thank you very much! It works well and i have installed it now and it works well in CPU mode!
```bash
(base)images\dw_GPU> dw --out ./cy3_dw.tif ..\raw\cy3.tif ..\dw_iter=40\psf\dw_cy3_psf.tif --iter 5
Reading ..\raw\cy3.tif
Reading ..\dw_iter=40\psf\dw_cy3_psf.tif
Output: ./cy3_dw.tif(.log.txt)
image: [2304x2304x40], psf: [181x181x79], job: [2484x2484x118]
creating fftw3 plans ...
   c2r plan ...
   c2r inplace plan ...
   r2c plan ...
   r2c inplace plan ...
Iteration   5/  5, Idiv=7.718e+00
Done!
```
Sorry for disturbing but the GPU mode still met some problem:
```bash
(base) PS images\dw_GPU> dw --out ./cy5_dw.tif ..\raw\cy5.tif ..\dw_iter=40\psf\dw_cy5_psf.tif --iter 5 --gpu
Reading ..\raw\cy5.tif
Reading ..\dw_iter=40\psf\dw_cy5_psf.tif
Output: ./cy5_dw.tif(.log.txt)
Deconvolving using shbcl2 (using inplace)
image: [2304x2304x40], psf: [181x181x79], job: [2484x2484x118]
Warning: could not determine your home directory
.
```

**Comment by Tangmc-kawa** [comment] 2024-06-04 02:49
And I can see the GPU is loaded:
![image](https://github.com/elgw/deconwolf/assets/79560566/06cec936-c87f-4d6f-8bb1-43f2b4805414)

**Comment by elgw** [comment] 2024-06-04 06:49
You will have to provide more details.
- What did you expect to happen and what happened? (did it stale?)
- If there is a log file (<input>.log.txt) please paste it here.
- Possibly also run with `--verbose 3` to see if there are any relevant messages.

The `Warning: could not determine your home directory` is nothing to worry about (it is one of those features missing in the windows version).

**Comment by Tangmc-kawa** [comment] 2024-06-04 09:07
It was locked here for hours and no output.
the log.txt is:
```bash
2024-06-04T17:04:16
> Settings:
image:  ..\raw\cy5.tif
psf:    ..\dw_iter=40\psf\dw_cy5_psf.tif
output: ./cy5_dw.tif
log file: ./cy5_dw.tif.log.txt
nIter:  5
nThreads for FFT: 8
nThreads for OMP: 8
verbosity: 3
background level: auto
method: Scaled Heavy Ball + OpenCL (SHBCL2)
metric: Idiv
Stopping after 5 iterations
overwrite: NO
tiling: OFF
XY crop factor: 0.001000
Offset: 5.000000
Output Format: 16 bit integer
Scaling: Automatic
Border Quality: 2 Minimal boundary artifacts
FFT lookahead: 0
FFTW3 plan: FFTW_MEASURE
Initial guess: Flat average
deconwolf: '0.4.0'
PWD: F:\spatial_data\processed\20240526_PRISM30_3D_IOH_processed\airlocalize_stack\T0001\C001\dw_GPU
CMD: D:\deconwolf\dw.exe --out ./cy5_dw.tif ..\raw\cy5.tif ..\dw_iter=40\psf\dw_cy5_psf.tif --iter 5 --gpu --verbose 3
BUILD_DATE: 'Jun  1 2024'
TIFF Backend: 'LIBTIFF, Version 4.6.0
Copyright (c) 1988-1996 Sam Leffler
Copyright (c) 1991-1996 Silicon Graphics, Inc.'
OpenMP: YES
OpenCL: YES
VkFFT: YES
sizeof(int) = 4
sizeof(float) = 4
sizeof(double) = 8
sizeof(size_t) = 8

Set the number of OMP threads to 8
Using static scheduling for OMP
Warning: TIFFTAG_SAMPLEFORMAT not specified, assuming uint but that could be wrong!
 TIFFTAG_BITSPERSAMPLE: 16
 size: 2304 x 2304, 16 bits
 # strips: 2304 
 strip size (ssize): 4608 bytes 
 # dirs (slices): 40
ReadUint ...
Done reading
 TIFFTAG_BITSPERSAMPLE: 32
 size: 181 x 181, 32 bits
 # strips: 17 
 strip size (ssize): 7964 bytes 
 # dirs (slices): 79
ReadFloat ...
Done reading
FFTW wisdom file: fftw_wisdom_float_inplace_threads_8.dat
Importing FFTW wisdom
Deconvolving with shbcl2
image: [2304x2304x40]
psf: [181x181x79]
job: [2484x2484x118] (728090208 voxels)
```
and verbose 3 shows:
```bash
(base) PS images\dw_GPU> dw --out ./cy5_dw.tif ..\raw\cy5.tif ..\dw_iter=40\psf\dw_cy5_psf.tif --iter 5 --gpu --verbose 3
Command line arguments accepted
> Settings:
image:  ..\raw\cy5.tif
psf:    ..\dw_iter=40\psf\dw_cy5_psf.tif
output: ./cy5_dw.tif
log file: ./cy5_dw.tif.log.txt
nIter:  5
nThreads for FFT: 8
nThreads for OMP: 8
verbosity: 3
background level: auto
method: Scaled Heavy Ball + OpenCL (SHBCL2)
metric: Idiv
Stopping after 5 iterations
overwrite: NO
tiling: OFF
XY crop factor: 0.001000
Offset: 5.000000
Output Format: 16 bit integer
Scaling: Automatic
Border Quality: 2 Minimal boundary artifacts
FFT lookahead: 0
FFTW3 plan: FFTW_MEASURE
Initial guess: Flat average

deconwolf: '0.4.0'
BUILD_DATE: 'Jun  1 2024'
TIFF Backend: 'LIBTIFF, Version 4.6.0
Copyright (c) 1988-1996 Sam Leffler
Copyright (c) 1991-1996 Silicon Graphics, Inc.'
OpenMP: YES
OpenCL: YES
VkFFT: YES
sizeof(int) = 4
sizeof(float) = 4
sizeof(double) = 8
sizeof(size_t) = 8

Image dimensions: 2304 x 2304 x 40
Reading ..\raw\cy5.tif
Reading ..\dw_iter=40\psf\dw_cy5_psf.tif
PSF X-crop: Not cropping
Output: ./cy5_dw.tif(.log.txt)
Deconvolving using shbcl2 (using inplace)
Setting the background level to 70.000000
image: [2304x2304x40], psf: [181x181x79], job: [2484x2484x118]
Found 1 CL platforms
Found 1 CL devices
Will use device 0 (first = 0)
CL device #0
CL_DEVICE_TYPE=CL_DEVICE_TYPE_GPU
CL_DEVICE_GLOBAL_MEM_SIZE = 25769148416 (25769 MiB)
CL_DEVICE_NAME = NVIDIA GeForce RTX 3090
CL_DEVICE_VENDOR = NVIDIA Corporation
CL_DRIVER_VERSION = 551.23
CL_DEVICE_EXTENSIONS = cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid cl_khr_pci_bus_info cl_khr_external_semaphore cl_khr_external_memory cl_khr_external_semaphore_win32 cl_khr_external_memory_win32
CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS=4099
Using VkFFT version 10303
Preparing for convolutions of size 2484 x 2484 x 118
Warning: could not determine your home directory
vkFFT cache file: VkFFT_kernelCache_2484x2484x118.binary
Initializing VkFFT for size 2484 x 2484 x 118
VkFFT intialization took 0.056611 s
fimcl_new, type=real
Creating cl buffer
Uploading data to GPU
Upload complete
fimcl_fft_inplace
VkFFTAppend (for in-place forward transform)
fimcl_new, type=real
Creating cl buffer
Uploading data to GPU
Upload complete
.Creating weight map for boundary handling
fimcl_new, type=real
Creating cl buffer
Uploading data to GPU
Upload complete
fimcl_fft_inplace
VkFFTAppend (for in-place forward transform)
fimcl_convolve
```
and locked here.

**Comment by elgw** [comment] 2024-06-05 07:24
That was something new :(

The image that you supplied is rather big, possibly there isn't enough memory on the GPU. And when memory runs out, dw will often just crash in an unpredictable way.

Out of curiosity, does it work with
1. Using --bq 0 or --bq 1 ?
2. Using a smaller image?
3. Using --tilepad 1024 ?

Regardless of that I will
- update VkFFT to the latest version.
- Inspect the fimcl_convolve code to see if there is anything suspicious.
- Add some more debug messages so that it can be pin-pointed.

Hope to have that ready next week.

Erik

**Comment by Tangmc-kawa** [comment] 2024-06-05 10:17
Thanks, I will try them on soon.

**Comment by Tangmc-kawa** [comment] 2024-06-05 13:22
I tried to build it on windows without using the installer so that i can update the packages mysilf, but this happens:
```bash
(base) PS E:\TMC\sources\deconwolf\build> cmake "-DCMAKE_TOOLCHAIN_FILE=E:/TMC/sources/vcpkg/scripts/buildsystems/vcpkg.cmake" -T ClangCL -A x64 ../
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- The C compiler identification is Clang 17.0.3 with MSVC-like command-line
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/Microsoft Visual Studio/2022/Community/VC/Tools/Llvm/x64/bin/clang-cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type: Release
-- The CXX compiler identification is Clang 17.0.3 with MSVC-like command-line
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Microsoft Visual Studio/2022/Community/VC/Tools/Llvm/x64/bin/clang-cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Enabling IPO
getopt found at: E:/TMC/sources/vcpkg/installed/x64-windows/debug/lib/getopt.lib
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Found FFTW: E:/TMC/sources/vcpkg/installed/x64-windows/include  found components: FLOAT_LIB
-- Found TIFF: D:/anacocnda3/Library/lib/cmake/tiff (found version "4.5.1")
-- Found GSL: E:/TMC/sources/vcpkg/installed/x64-windows/include (found version "2.8")
-- Looking for CL_VERSION_3_0
-- Looking for CL_VERSION_3_0 - found
-- Found OpenCL: E:/TMC/sources/vcpkg/installed/x64-windows/debug/lib/OpenCL.lib (found version "3.0")
Will use OpenCL
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND)
OpenMP not found automatically, trying manual
Enabling IPO
-- Configuring done (50.2s)
-- Generating done (0.0s)
-- Build files have been written to: E:/TMC/sources/deconwolf/build
```
and when i compile the INSTALL project, it shows:
![image](https://github.com/elgw/deconwolf/assets/79560566/0433fc5c-bb20-4cf1-9617-c7f1ffc904c5)

**Comment by Tangmc-kawa** [comment] 2024-06-05 13:24
And I have assure that the GPU usage error is not caused by figure size because the demo figure dapi.tif also locked at the same point.

**Comment by Tangmc-kawa** [comment] 2024-06-05 13:25
I am sorry that I don't know how to Inspect the `fimcl_convolve` code because I didn't learn c :( . I will keep trying.

**Comment by elgw** [comment] 2024-06-05 14:07
Good to know that it isn't about the image size.

I'm not near any windows computer today so this will be just as I remember it:

For the compilation related to fftw try installing both of these:
```
.\vcpkg\vcpkg.exe install fftw3[threads]
.\vcpkg\vcpkg.exe install fftw3f[threads]
```

if they really are installed, and it still does not work you will have to tell the linker where the lib files are manually:

I.e. under Linker->Input->Additional dependencies add the folloing (adjust for your actual paths):
```
C:\Users\erikw\Desktop\dw-windows\vcpkg\installed\x64-windows\lib\fftw3.lib
C:\Users\erikw\Desktop\dw-windows\vcpkg\installed\x64-windows\lib\fftw3f.lib
```

I'm not sure why it isn't linking to openmp, I thought that it would with the updated cmake file...

The remedy as I remember it was to go to Linker->Input->Additional dependencies again and add the following:

`libomp.lib`

I'm sorry for all the trouble this is causing you, thanks for your persistence :)

Cheers,
Erik

**Comment by Tangmc-kawa** [comment] 2024-06-05 14:11
Thanks, I will try it on.

**Comment by elgw** [comment] 2024-06-17 12:36
I'm closing this issues since there are now downloadable binaries for windows under [releases](https://github.com/elgw/deconwolf/releases).

**Closed by elgw** 2024-06-17 12:36 UTC
Labels: enhancement, help wanted
